### ISSUE TITLE
ONLY two components included?

### ISSUE THREAD

**Issue by xiongchengqing** [grommet/next-sample#2] opened 2017-07-24 08:35 UTC
ONLY two components included?

**Comment by alansouzati** [comment] 2017-07-24 16:42
:) Yeah we just started working on Grommet 2.0.

I'm expecting to have a lot more during this month. We intentionally chose 2 components to test the new architecture, we pretty excited about it.

I'm closing this issue since it is not a bug, but feel free to continue the discussion here.

**Closed as completed by alansouzati** 2017-07-24 16:42 UTC
